# Generated by Django 4.0.3 on 2022-03-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nome',
            new_name='descricao',
        ),
    ]
