# Generated by Django 4.0.3 on 2022-03-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='motivo',
            field=models.CharField(default='Nenhum', max_length=100),
        ),
    ]
